apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao
spec:
  replicas: 5
  selector:
    matchLabels:
      app: conversao
  template:
    metadata:
      labels:
        app: conversao
    spec:
      containers:
        - name: conversao
          image: nginx
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: conversao
spec:
  selector:
    app: conversao
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP